"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
require("dotenv/config");
const auth_route_1 = __importDefault(require("./src/routes/auth.route"));
const halaqah_route_1 = __importDefault(require("./src/routes/halaqah.route"));
const santri_route_1 = __importDefault(require("./src/routes/santri.route"));
const error_handler_1 = require("./src/middleware/error.handler");
const setoran_route_1 = __importDefault(require("./src/routes/setoran.route"));
const absensi_route_1 = __importDefault(require("./src/routes/absensi.route"));
const display_route_1 = __importDefault(require("./src/routes/display.route"));
const cors_1 = __importDefault(require("cors"));
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use("/api/halaqah/auth", auth_route_1.default);
app.use("/api/halaqah", halaqah_route_1.default);
app.use("/api/santri", santri_route_1.default);
app.use("/api/setoran", setoran_route_1.default);
app.use("/api/absensi", absensi_route_1.default);
app.use("/api/display", display_route_1.default);
app.use(error_handler_1.errorHandler);
exports.default = app;
